---
title: "Worst Airports"
output: md_document
---

## Including Plots

You can also embed plots, for example:

```{r echo=FALSE}

library(tidyverse)
library(mosaic)
library(airportr)
library(dplyr)
library(usmap)
library(maptools)
library(ggplot2)
library(rgdal)
library(viridis)
library(here)
library(colorspace)

ABIA <- read.csv(here("Data/ABIA.csv"))

## Let's take a look at what average delays look like for flights out of Austin 

ABIA_stats = ABIA %>% 
  filter(Origin == 'AUS') %>% 
  group_by(Dest) %>% 
  summarize(count = n(),
            mean_arr_delay = mean(ArrDelay, na.rm=TRUE)) %>% 
  filter(count > 499)

ggplot(ABIA_stats) +
  geom_col(aes(x = mean_arr_delay, fct_reorder(Dest, mean_arr_delay), fill = mean_arr_delay), show.legend = FALSE) +
  scale_fill_continuous_sequential(palette = "Heat"
                                    )  +
  theme_classic() +
  labs(title = "Worst Arrival Delays by Airport",
       subtitle = "Arriving from Austin (At Least 500 Flights)",
       x = "Average Flight Delay",
       y = "Destination") +
  geom_vline(aes(xintercept=5.5546)) +
  geom_text(mapping=aes(x=5.5546, y=5, label="Group Average"), size=4, angle=90, vjust=-.3, hjust=.3)

```


## Including Plots

You can also embed plots, for example:

```{r echo=FALSE}

## Let's also have only Austin outgoing flights
airports <- airports %>% 
  rename(Dest = IATA)

ABIA_outbound <- ABIA %>% 
  filter(Origin == 'AUS')

## Let's join our tables

ABIA_locations <- inner_join(x = ABIA_outbound, y = airports, by = 'Dest')


## We need to reorganize the data and map it to the usmap package:
ABIA_locations <- ABIA_locations %>%           
  dplyr::select("Latitude", everything()) %>%       # Reorder LAT
  dplyr::select("Longitude", everything()) %>%      # Reorder LONG
  group_by(Longitude, Latitude, Dest) %>%           #Only 100+ flight destinations
  summarize(count = n(),
            mean_arr_delay = mean(ArrDelay, na.rm=TRUE)) %>% 
  filter(count > 499)

ABIA_transformed <- usmap_transform(ABIA_locations)

## Let's select our hubs for labels

ABIA_hubs <- ABIA_transformed %>% 
  filter(Dest == "DEN" |
           Dest == "DAL" |
           Dest == "ORD" |
           Dest == "ATL" |
           Dest == "CLT")

## Plot to our map

plot_usmap() +
  geom_point(data = ABIA_transformed, aes(x = Longitude.1, y = Latitude.1, colour = mean_arr_delay, size = mean_arr_delay),
             alpha = 0.8) +
  scale_color_continuous_sequential(palette = "Heat", guide = "legend") +
  scale_size_continuous(range = c(1, 25)) +
  ggrepel::geom_label_repel(data = ABIA_hubs,
                            aes(x = Longitude.1, y = Latitude.1, label = Dest),
                            size = 3, alpha = 0.8,
                            label.r = unit(0.5, "lines"), label.size = 0.5,
                            segment.color = "red", segment.size = 1,
                            seed = 1002) +
  labs(title = "Worst Arrival Delays by Airport",
       subtitle = "Arriving from Austin (At Least 500 Flights)"
       ) + 
  theme(legend.position = "right") +
  guides(size=guide_legend(title="Arrival Delay"), color=guide_legend(title="Arrival Delay"))

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
